name: Release

on:
  push:
    tags:
      - "*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read changlog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref_name }}
          path: docs/changelog.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          name: 'v${{ github.ref_name }}'
